name: CareAlert
description: Safety and emergency alert application
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    uuid: ^4.0.0

    # Firebase Core (Required for all Firebase services)
    firebase_core: ^3.6.0
    firebase_auth: ^5.3.1
    firebase_messaging: ^15.1.3
    firebase_storage: ^12.3.4
    cloud_firestore: ^5.4.4

    # Location Services
    geolocator: ^10.1.0
    geocoding: ^2.1.1
    permission_handler: ^11.1.0

    image_picker: ^1.0.7

    # Local Storage
    shared_preferences: ^2.3.3

    # HTTP & Communication
    http: ^1.1.2
    url_launcher: ^6.2.2

    # State Management
    provider: ^6.1.2

    # UI Components
    cupertino_icons: ^1.0.6
    intl: ^0.18.1

    # Background Tasks
    workmanager: ^0.9.0+3
    connectivity_plus: ^5.0.0

    # Functional Programming
    dartz: ^0.10.1

    # Onboarding Screens
    introduction_screen: ^4.0.0
    floating_bottom_navigation_bar: ^1.5.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
